
interface BloodPressureReportData {
  patientName: string;
  examDate: string;
  systolic: number;
  diastolic: number;
}

export const generateBloodPressureReport = (data: BloodPressureReportData, language: 'en' | 'es') => {
  const { patientName, examDate, systolic, diastolic } = data;
  
  const getStatus = () => {
    if (systolic < 120 && diastolic < 80) return { status: language === 'en' ? "Normal" : "Normal", icon: "✓" };
    if (systolic >= 120 && systolic < 130 && diastolic < 80) return { status: language === 'en' ? "Elevated" : "Elevada", icon: "!" };
    if (systolic >= 130 && systolic < 140 || diastolic >= 80 && diastolic < 90) return { status: language === 'en' ? "Stage 1 Hypertension" : "Hipertensión Etapa 1", icon: "⚠" };
    if (systolic >= 140 || diastolic >= 90) return { status: language === 'en' ? "Stage 2 Hypertension" : "Hipertensión Etapa 2", icon: "⚠⚠" };
    if (systolic >= 180 || diastolic >= 120) return { status: language === 'en' ? "Hypertensive Crisis" : "Crisis Hipertensiva", icon: "🚨" };
    return { status: language === 'en' ? "Unknown" : "Desconocido", icon: "?" };
  };

  const { status, icon } = getStatus();

  const content = {
    en: {
      title: "BLOOD PRESSURE REPORT",
      date: "Date",
      patient: "Patient Name",
      provider: "Healthcare Provider",
      reading: "Blood Pressure Reading",
      systolic: "Systolic",
      diastolic: "Diastolic",
      status: "Status",
      recommendation: "Recommendations",
      followUp: "Follow-up Instructions",
      emergency: "If you experience severe headache, vision problems, or chest pain, seek immediate medical attention.",
      disclaimer: "This report is for informational purposes only and does not constitute medical advice.",
      signature: "Generated by Healthcare System",
      normalRange: "Normal Range: Less than 120/80 mmHg",
      nextSteps: "Next Steps",
    },
    es: {
      title: "INFORME DE PRESIÓN ARTERIAL",
      date: "Fecha",
      patient: "Nombre del Paciente",
      provider: "Proveedor de Salud",
      reading: "Lectura de Presión Arterial",
      systolic: "Sistólica",
      diastolic: "Diastólica",
      status: "Estado",
      recommendation: "Recomendaciones",
      followUp: "Instrucciones de Seguimiento",
      emergency: "Si experimenta dolor de cabeza severo, problemas de visión o dolor en el pecho, busque atención médica inmediata.",
      disclaimer: "Este informe es solo para fines informativos y no constituye consejo médico.",
      signature: "Generado por Sistema de Salud",
      normalRange: "Rango Normal: Menos de 120/80 mmHg",
      nextSteps: "Próximos Pasos",
    }
  };

  const t = content[language];

  return `
${t.title}
----------------------------------------

${t.date}: ${examDate}
${t.patient}: ${patientName}
${t.provider}: Dr. Smith

${t.reading}
----------------------------------------
${t.systolic}: ${systolic} mmHg
${t.diastolic}: ${diastolic} mmHg
${t.status}: ${icon} ${status}
${t.normalRange}

${t.recommendation}
----------------------------------------
${getRecommendations(systolic, diastolic, language)}

${t.followUp}
----------------------------------------
* ${language === 'en' ? 'Schedule follow-up appointment in 2 weeks' : 'Programar cita de seguimiento en 2 semanas'}
* ${language === 'en' ? 'Monitor blood pressure daily' : 'Monitorear la presión arterial diariamente'}
* ${language === 'en' ? 'Maintain blood pressure log' : 'Mantener registro de presión arterial'}

${t.emergency}

----------------------------------------
${t.disclaimer}
${t.signature}
`;
};

const getRecommendations = (systolic: number, diastolic: number, language: 'en' | 'es') => {
  const recommendations = {
    en: {
      lifestyle: [
        '* Maintain a healthy diet low in sodium',
        '* Regular physical activity (30 minutes daily)',
        '* Limit alcohol consumption',
        '* Quit smoking if applicable',
        '* Manage stress levels'
      ],
      medication: '* Continue prescribed medications as directed',
      monitoring: '* Monitor blood pressure regularly'
    },
    es: {
      lifestyle: [
        '* Mantener una dieta saludable baja en sodio',
        '* Actividad física regular (30 minutos diarios)',
        '* Limitar el consumo de alcohol',
        '* Dejar de fumar si aplica',
        '* Manejar niveles de estrés'
      ],
      medication: '* Continuar medicamentos según lo prescrito',
      monitoring: '* Monitorear la presión arterial regularmente'
    }
  };

  const r = recommendations[language];
  return `${r.lifestyle.join('\n')}\n${r.medication}\n${r.monitoring}`;
};
